"""Validator + injector for the Wilde Circle web.

Reads data/works.json + data/people/*.json + data/relationships/*.json,
validates the corpus against the house rules (README.md), and splices the
merged object into WILDE-CIRCLE_web.html between the CIRCLE_DATA markers.

Usage:
  python build_circle_web.py            # validate + inject
  python build_circle_web.py --stats    # validate + dashboard only, no write
  python build_circle_web.py --allow-dirty   # let needs-fix/rejected quotes through

UTF-8 without BOM throughout (never PowerShell Set-Content on these files).
"""
import argparse
import json
import re
import sys
from collections import Counter
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent
HTML = ROOT / "WILDE-CIRCLE_web.html"
BEGIN = "/* ===BEGIN CIRCLE_DATA (generated by build_circle_web.py - do not hand-edit)=== */"
END = "/* ===END CIRCLE_DATA=== */"

CERTAINTY = {"self-reported", "second-hand", "uncorroborated", "marriage", "desire-expressed"}
OUTCOMES = {"declined", "unknown", "unreciprocated"}
CERTAINTY_STATUS = {"proposed", "confirmed"}
VERIFICATION = {"verified-exact", "verified-elision", "needs-fix", "rejected", "unverified"}
HOW = {"pdf-at-page", "repo-file", "archive-org", "web", "unverified"}
LOCATOR_TYPES = {"page", "diary-entry", "trial-day", "letter-date", "none"}
GROUPS = {"core", "family", "society", "aesthete", "trials", "chaeronea",
          "later", "liaisons", "beyond"}
GENDERS = {"m", "f", None}
STATUS_CHAR = {"verified-exact": "ok", "verified-elision": "ok", "needs-fix": "dirty",
               "rejected": "dirty", "unverified": "pending"}


def load_json(p: Path):
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception as e:  # noqa: BLE001 - report and count as fatal
        return {"__load_error__": f"{p.name}: {e}"}


def check_date(d, where, errors):
    if d is None:
        return
    if not isinstance(d, dict):
        errors.append(f"{where}: date must be an object or null")
        return
    bad = {k for k in ("year", "month", "day") if k in d}
    if bad:
        errors.append(f"{where}: date uses {sorted(bad)}; the renderer reads y/m/d "
                      f"- such a date silently displays as 'date unknown'")
        return
    y = d.get("y")
    if y is not None and not (1700 < y < 2000):
        errors.append(f"{where}: implausible year {y}")


def validate(works, people, rels):
    errors, warnings = [], []
    pids = set()
    for p in people:
        if "__load_error__" in p:
            errors.append(p["__load_error__"])
            continue
        pid = p.get("id", "?")
        if pid in pids:
            errors.append(f"duplicate person id {pid}")
        pids.add(pid)
        if p.get("group") not in GROUPS:
            errors.append(f"{pid}: bad group {p.get('group')}")
        if p.get("gender") not in GENDERS:
            errors.append(f"{pid}: bad gender {p.get('gender')} (m / f / null)")
        check_date(p.get("born"), f"{pid}.born", errors)
        check_date(p.get("died"), f"{pid}.died", errors)
        for ce in p.get("context_engagements", []) or []:
            if not (ce.get("partner_name") or "").strip():
                errors.append(f"{pid}: context_engagement missing partner_name "
                              f"(note: {(ce.get('note') or '')[:60]!r})")
            if "name" in ce:
                errors.append(f"{pid}: context_engagement uses 'name'; the field is 'partner_name'")
            for q in ce.get("sources", []) or []:
                validate_quote(q, f"{pid}.context[{ce.get('partner_name')}]", works, errors)

    rids = set()
    for r in rels:
        if "__load_error__" in r:
            errors.append(r["__load_error__"])
            continue
        rid = r.get("id", "?")
        if rid in rids:
            errors.append(f"duplicate relationship id {rid}")
        rids.add(rid)
        ppl = r.get("people", [])
        if len(ppl) != 2 or sorted(ppl) != ppl:
            errors.append(f"{rid}: people must be 2 ids in sorted order")
        if rid != "--".join(ppl):
            errors.append(f"{rid}: id does not match people {ppl}")
        for pid in ppl:
            if pid not in pids:
                errors.append(f"{rid}: unknown person {pid}")
        if r.get("certainty") not in CERTAINTY:
            errors.append(f"{rid}: bad certainty {r.get('certainty')}")
        if r.get("certainty_status") not in CERTAINTY_STATUS:
            errors.append(f"{rid}: bad certainty_status")
        if r.get("certainty") == "uncorroborated" and not r.get("disputed"):
            errors.append(f"{rid}: uncorroborated requires a disputed block")
        if r.get("certainty") == "desire-expressed":
            if r.get("direction") not in ppl:
                errors.append(f"{rid}: desire-expressed requires direction = one of {ppl}")
            if r.get("outcome") not in OUTCOMES:
                errors.append(f"{rid}: desire-expressed requires outcome in {sorted(OUTCOMES)}")
        else:
            if r.get("direction") is not None and r.get("direction") not in ppl:
                errors.append(f"{rid}: direction must name one of {ppl}")
            if r.get("outcome") is not None:
                errors.append(f"{rid}: outcome is only for desire-expressed edges")
        check_date(r.get("start"), f"{rid}.start", errors)
        check_date(r.get("end"), f"{rid}.end", errors)
        s, e = r.get("start") or {}, r.get("end") or {}
        if s.get("y") and e.get("y") and s["y"] > e["y"]:
            errors.append(f"{rid}: start after end")
        if not r.get("sources"):
            warnings.append(f"{rid}: no sources at all")
        for q in r.get("sources", []) or []:
            validate_quote(q, rid, works, errors)
    return errors, warnings, pids


def validate_quote(q, where, works, errors):
    v = q.get("verification")
    if v not in VERIFICATION:
        errors.append(f"{where}: bad verification {v}")
    if q.get("how_verified") not in HOW:
        errors.append(f"{where}: bad how_verified {q.get('how_verified')}")
    if q.get("locator_type", "page") not in LOCATOR_TYPES:
        errors.append(f"{where}: bad locator_type")
    if v in {"verified-exact", "verified-elision"} and not (q.get("provenance") or "").strip():
        errors.append(f"{where}: verified quote with empty provenance")
    if (q.get("quote") or "") == "" and v not in {None, "unverified"}:
        errors.append(f"{where}: pointer (empty quote) must be unverified")
    wk = q.get("work")
    if wk and wk not in works:
        errors.append(f"{where}: unknown work key {wk} (add to works.json)")


def dashboard(people, rels):
    vq = Counter()
    pointers = 0
    for r in rels:
        for q in r.get("sources", []) or []:
            vq[q.get("verification", "unverified")] += 1
            if (q.get("quote") or "") == "":
                pointers += 1
    cert = Counter(r.get("certainty") for r in rels)
    status = Counter(p.get("research_status", "stub") for p in people)
    lines = [
        f"people: {len(people)}  ({dict(status)})",
        f"relationships: {len(rels)}  by certainty: {dict(cert)}",
        f"quotes: {sum(vq.values())}  by verification: {dict(vq)}  pointers: {pointers}",
    ]
    return "\n".join(lines), vq


def inject(payload: str) -> None:
    html = HTML.read_text(encoding="utf-8")
    if BEGIN not in html or END not in html:
        sys.exit(f"markers not found in {HTML.name}")
    pre, rest = html.split(BEGIN, 1)
    _, post = rest.split(END, 1)
    HTML.write_text(pre + BEGIN + "\n" + payload + "\n" + END + post, encoding="utf-8")


def write_ledger(works, rels) -> None:
    """One-time generation of the audit ledger from the corpus (hand-maintained after)."""
    out = ROOT / "audits" / "QUOTE-AUDIT_circle.md"
    lines = [
        "# Quote audit — Wilde Circle",
        "",
        "Legend (house): ✓ verified exact · ✓* verified, honest elision · ! verified but needs a wording/framing fix · ✗ error/rejected · ⧖ not yet audited",
        "",
        "Generated from the JSON corpus on 2026-08-03; **hand-maintained thereafter** (do not regenerate over recorded verdicts — record a verdict here, mirror it into the JSON `verification` field, rebuild the HTML). The Status column below is the HUMAN verdict: every row starts ⧖ regardless of the agent's transcription status; the Agent column records what the research pass did.",
        "",
        "Scope of the human pass (Lovelle): 100% of `alleged`/`disputed`/`propositioned-declined` quotes and any quote a certainty classification rests on; spot-check ~20% of the rest; every `certainty_status: proposed → confirmed` flip.",
        "",
    ]
    agent_mark = {"verified-exact": "agent ✓ at-page", "verified-elision": "agent ✓* at-page",
                  "unverified": "agent ⧖", "needs-fix": "agent !", "rejected": "agent ✗"}
    for r in sorted(rels, key=lambda x: x.get("id", "")):
        if "__load_error__" in r:
            continue
        lines.append(f"## {r['id']}  ·  {r.get('certainty')} ({r.get('certainty_status')})")
        lines.append("")
        lines.append("| Quote (first words …) | Source (at-page) | Agent | Status | Note |")
        lines.append("|---|---|---|---|---|")
        for q in r.get("sources", []) or []:
            first = (q.get("quote") or "").replace("\n", " ")[:60]
            first = first + " …" if first else "[POINTER] " + (q.get("supports") or "")[:60]
            wk = works.get(q.get("work") or "", {})
            src = f"{wk.get('short_cite', q.get('work') or '—')}{', ' + q['locator'] if q.get('locator') else ''}"
            lines.append(f"| {first} | {src} | {agent_mark.get(q.get('verification'), '?')} | ⧖ | |")
        lines.append("")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"ledger written: {out.name} ({len(rels)} sections)")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--stats", action="store_true")
    ap.add_argument("--allow-dirty", action="store_true")
    ap.add_argument("--ledger", action="store_true",
                    help="one-time: regenerate audits/QUOTE-AUDIT_circle.md from the corpus")
    args = ap.parse_args()

    works = json.loads((ROOT / "data" / "works.json").read_text(encoding="utf-8"))
    people = [load_json(p) for p in sorted((ROOT / "data" / "people").glob("*.json"))]
    rels = [load_json(p) for p in sorted((ROOT / "data" / "relationships").glob("*.json"))]

    errors, warnings, _ = validate(works, people, rels)
    dash, vq = dashboard(people, rels)
    print(dash)
    for w in warnings:
        print(f"  warn: {w}")
    if errors:
        print("VALIDATION ERRORS:")
        for e in errors:
            print(f"  ERROR: {e}")
        sys.exit(1)
    dirty = vq.get("needs-fix", 0) + vq.get("rejected", 0)
    if dirty and not args.allow_dirty:
        sys.exit(f"{dirty} needs-fix/rejected quotes - resolve or pass --allow-dirty")
    if args.ledger:
        write_ledger(works, [r for r in rels if "__load_error__" not in r])
    if args.stats:
        return

    circle = {
        "people": [p for p in people if "__load_error__" not in p],
        "relationships": [r for r in rels if "__load_error__" not in r],
        "works": works,
        "built": date.today().isoformat(),
    }
    payload = "const CIRCLE = " + json.dumps(
        circle, ensure_ascii=False, separators=(",", ":")
    ).replace("</", "<\\/").replace("\u2028", "\\u2028").replace("\u2029", "\\u2029") + ";"
    inject(payload)
    print(f"injected {len(payload)/1024:.0f} KB into {HTML.name}")


main()
